# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-13 21:05
from __future__ import unicode_literals

from django.db import migrations, models
from django.contrib.postgres.operations import CreateExtension
import mozio.apps.providers.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        CreateExtension('postgis'),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('Id', models.CharField(default=uuid.uuid4, max_length=96, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=1024)),
                ('Email', models.CharField(max_length=2048, validators=[mozio.apps.providers.models.emailValidator])),
                ('PhoneNumber', models.CharField(max_length=32, validators=[mozio.apps.providers.models.phoneNumberValidator])),
                ('Language', models.CharField(max_length=16)),
                ('Currency', models.CharField(max_length=16)),
            ],
        ),
    ]
