# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-13 23:49
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=2048)),
                ('Price', models.FloatField()),
                ('Polygon', django.contrib.gis.db.models.fields.PolygonField(db_index=True, srid=4326)),
                ('Provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.Provider')),
            ],
        ),
    ]
